### ISSUE TITLE
Setting up CWT for Linux

### ISSUE THREAD

**Issue by Melvasul** [cwtools/cwtools#31]
Hello there :)

I've tried to setup CWT on Linux, using VSC but I'm having only one problem:
1. autocompletion
2. the extension only checks errors in the localisation files

mod path: `/home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/`
for the installation of EUIV I've found 2 path:
1. `/home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV`
2. `/home/atimpone/.steam/steam/steamapps/common/Europa Universalis IV`

I've tried, as Vanilla EU4 (extension settings) to put both above, not at the same time obvs, and it has generated the vanilla file every time correctly (is there a way to make it build once again?) but after that, I just get this:

```
[Info  - 11:11:36] repo path "https://github.com/tboby/cwtools-eu4-config"
[Info  - 11:11:36] Client thinks this is a vanilla directory
[Info  - 11:11:36] New init { processId = Some 4087
  rootUri =
           Some
             file:///home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV
  initializationOptions =
                         Some
                           {
  "language": "eu4",
  "isVanillaFolder": true,
  "rulesCache": "/home/atimpone/.vscode/extensions/tboby.cwtools-vscode-0.8.41/.cwtools",
  "rules_version": "latest",
  "repoPath": "https://github.com/tboby/cwtools-eu4-config"
}
  capabilitiesMap =
                   map
                     [("textDocument.codeAction.dynamicRegistration", true);
                      ("textDocument.codeLens.dynamicRegistration", true);
                      ("textDocument.colorProvider.dynamicRegistration", true);
                      ("textDocument.completion.completionItem.commitCharactersSupport",
                       true);
                      ("textDocument.completion.completionItem.deprecatedSupport",
                       true);
                      ("textDocument.completion.completionItem.preselectSupport",
                       true);
                      ("textDocument.completion.completionItem.snippetSupport",
                       true); ("textDocument.completion.contextSupport", true);
                      ("textDocument.completion.dynamicRegistration", true); ...]
  trace = Some Off
  workspaceFolders =
                    [{ uri =
                            file:///home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV
                       name = "Europa Universalis IV" };
                     { uri =
                            file:///home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster
                       name = "missionsmaster" };
                     { uri =
                            file:///home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV
                       name = "Europa Universalis IV" }] }
[Info  - 11:11:36] New configuration { settings =
            {
  "cwtools": {
    "trace": {
      "server": "off"
    },
    "localisation": {
      "languages": [
        "English"
      ],
      "generated_strings": ":0 \"REPLACE_ME\"",
      "replaceme": ""
    },
    "errors": {
      "vanilla": "false",
      "ignore": [],
      "ignorefiles": [
        "README.txt",
        "credits.txt",
        "credits_l_simp_chinese.txt",
        "reference.txt",
        "startup_info.txt"
      ]
    },
    "experimental": "false",
    "debug_mode": "false",
    "rules...}
[Info  - 11:11:36] No cache path
[Diag - 11:11:36] queue length: 0
[Info  - 11:11:36] /home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV
[Info  - 11:11:36] Parse docs time: 1
[Info  - 11:11:36] Vanilla folder, so not loading cache
[Info  - 11:11:36] Parse cache time: 0
[Diag - 11:11:36] lint force: true, shallow: false
[Error - 11:11:36] cwtools git error, recovering, error: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-7ce88e6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-7ce88e6: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open_ext(git_repository*& repository, FilePath path, RepositoryOpenFlags flags, FilePath ceilingDirs)
   at LibGit2Sharp.Core.Proxy.git_repository_open_ext(String path, RepositoryOpenFlags flags, String ceilingDirs)
   at LibGit2Sharp.Repository.IsValid(String path)
   at Main.Git.initOrUpdateRules(String repoPath, String gameCacheDir, Boolean stable, Boolean first)
[Diag - 11:11:36] lint after delayed
[Diag - 11:11:36] queue length: 0
[Info  - 11:11:52] Workspace roots:
[Info  - 11:11:52] root /home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV, exists: true
[Info  - 11:11:52] root /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster, exists: true
[Info  - 11:11:52] root /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV, exists: true
[Info  - 11:11:52] embedded folder <null>
[Info  - 11:11:52] normalised /home/atimpone/.local/share/Steam/steamapps/common/Europa Universalis IV
[Info  - 11:11:52] normalised /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster
[Info  - 11:11:52] normalised /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV
[Info  - 11:11:57] Parsing 21304 files
```
after that, is just an endless repetition of `[Info  - 11:21:00] Unexpected scope RebelFaction` and 
```[Info  - 11:21:03] goto fn file:///home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster/missions/ME_Byzantium_Missions.txt
[Info  - 11:21:03] getInfo missions/ME_Byzantium_Missions.txt /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster/missions/ME_Byzantium_Missions.txt
[Info  - 11:21:04] symbolInfoAtPos missions/ME_Byzantium_Missions.txt /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster/missions/ME_Byzantium_Missions.txt
Looking for effect "none" in the 0 effects loaded
[Info  - 11:21:04] symbolInfoAtPos missions/ME_Byzantium_Missions.txt /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster/missions/ME_Byzantium_Missions.txt
Looking for effect "none" in the 0 effects loaded
[Diag - 11:21:05] lint after delayed
[Info  - 11:21:05] /home/atimpone/.local/share/Paradox Interactive/Europa Universalis IV/mod/missionsmaster/missions/ME_Byzantium_Missions.txt
[Info  - 11:21:05] Validating 1 files
[Info  - 11:21:05] Localisation check 1 files
[Info  - 11:21:05] Localisation check took 4ms
[Info  - 11:21:05] Update Time: 142
[Diag - 11:21:05] queue length: 0
```
![Screenshot from 2020-06-25 11-24-04](https://user-images.githubusercontent.com/11297488/85693342-74f9b580-b6d6-11ea-9201-310b52344bf0.png)

What should I fix?
Additional info:
1. Fedora 32
2. Gnome on Xorg (the game won't launch on Wayland)

**Comment by tboby** [comment]
The git library I'm using (which is basically the only one that exists, libgit2), doesn't appear to work on recent linux distributions, and the maintainers of the C# version don't seem to be in a hurry to fix it unfortunately.

There are two solutions:
1. Try and fix the dll problem. Set the `LD_DEBUG` it suggests, and see if you can figure out what the linking error is.
2. Manually clone and update the rules

For the latter:
1. Clone https://github.com/cwtools/cwtools-eu4-config to a folder
2. In settings, set `rules_version` to `manual` and `rules_folder` to that folder you just cloned.

You'll have to remember to update that git repository when the rules change unfortunately, but that doesn't happen too often :)

**Comment by Melvasul** [comment]
Ok, cloned into the Documents folder and set it up in the settings as you suggested `/home/atimpone/Documents/cwtools-eu4-config-master`

I let it run more than once (while closing and reopening the code every time) and it works, thank you ^^
